version: "3.9"

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
      args:
        EXTRAS: "ui"
    ports:
      - "8765:8765"
    volumes:
      - ./projects:/data/projects:ro
      - ./.classiflow:/data/.classiflow

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
      args:
        EXTRAS: "app"
    ports:
      - "8501:8501"
    volumes:
      - ./projects:/data/projects:ro
      - ./data:/data/input:ro
